features=["driver_gps_accuracy",
    "trip_distance",
    "hourofday",
    "hourofday_average",
    "driver_hourofday_average",
    "dayofweek",
    "dayofweek_average",
    "driver_dayofweek_average"
    ]

target="is_accepted"
test_size=0.2

[random_forest]
n_estimators=300
max_depth=30
n_jobs=-1
random_state=33
bootstrap=false
